apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: argocd-server-dtrl
  namespace: devops
spec:
  host: argocd-server.devops.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
